### ISSUE TITLE
Add Activity form Residents field jumps to first selected resident when making additional selection

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#169]
It has been reported and confirmed that the Add Activity form select menu jumps to the first selected resident when selecting subsequent residents:

![peek 2017-10-03 20-56](https://user-images.githubusercontent.com/17307/31140786-2b9d811e-a87e-11e7-9f28-ca65272ac7fb.gif)

This makes it somewhat difficult to select several residents, as the user must repeatedly scroll down.

# Upstream issue
There have been several upstream bug reports in the select2 project related to this issue. The most recent bug report and pull request are:

- https://github.com/select2/select2/issues/4417
- https://github.com/select2/select2/pull/4869

**Comment by alexweissman** [comment]
Unfortunately we can't merge in #4869 yet, because it doesn't take into account the infinite-scroll use case.

**Comment by brylie** [comment]
OK, thanks for the update @alexweissman :-)

**Comment by brylie** [comment]
We ended up reverting the multi-select widget (inadvertently), so I am closing this issue.
