### ISSUE TITLE
Take screenshots of updated UI components

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#31]
Over the past few months, there have been several improvements and additions to our UI components. Create screenshots of these UI components and add them to the project documentation. This task includes populating the platform with temporary data, so that the screenshots demonstrate live data.

# Criteria
* [ ] Screenshots exist for most or all significant UI components
  * [ ] Individual resident page
    * [ ] Activity trend chart
    * [ ] Activity calendar heatmap
    * [ ] Activity table
  * [ ] Home page
    * [ ] Residents status indicators
    * [ ] Residents activity status trend graph
  * [ ] Homes page
  * [ ] Administrative dashboard (settings page)
  * [ ] Forms
    * [ ] Add activity form
    * [ ] Add resident form
  * [ ] Emotional wellbeing input (faces) 

# Related issues
* #32 - mock data scripts would help populate project with data for screenshots

**Comment by brylie** [comment]
@ErikPel this might also be a good starting point. It would ensure that you are able to get the platform running, can enter data as expected, and are familiar with the high-level organization of all pages. It would be beneficial from both documentation and user testing viewpoints.

**Comment by ErikPel** [comment]
@brylie I'll try to get it running tonight or tomorrow and then start working on it :)

**Comment by brylie** [comment]
Great, thanks! Please let me know if I can be of assistance. I may also available for a screen sharing/chat session.

**Comment by ErikPel** [comment]
@brylie Using something else to communicate than github issue comments would be great. Is there somewhere I can chat with you? Do you use IRC or skype or something?

**Comment by brylie** [comment]
I am 'brylie' on Freenode. Lets meet in #GeriLife?
