### ISSUE TITLE
Allow toggle between activity 'counts' and 'minutes' on Home Profile, Activities section

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#319]
The Home Profile, Activities section currently shows activity *counts* for the past 30 days, in several ways:

- by resident and type
- by activity type (all activities)
- by facilitator role (all activities)

![screenshot from 2019-01-27 11-58-54](https://user-images.githubusercontent.com/17307/51799557-f7a0eb80-222a-11e9-98d7-a9131e479140.png)

# Task
Allow users to toggle between activity *counts* and *minutes*, with a server method to prepare the data.

![screenshot from 2019-01-27 11-58-14](https://user-images.githubusercontent.com/17307/51799553-ddffa400-222a-11e9-81c5-31d572ad8642.png)

BONUS: allow the user to toggle between 7 and 30 day timespan:

![screenshot from 2019-01-27 11-54-07](https://user-images.githubusercontent.com/17307/51799547-c9bba700-222a-11e9-98da-81b293a266b2.png)

## Related issues
The following issues are related, and might be good to be done in conjunction with this one:
- #317 
- #318

**Comment by brylie** [comment]
I have started this task in another branch, and had some problems with Git rebase, so abandoned the branch. Feel free to find your own path here, if the code is easy to read and maintain.


Here are some code snippets you might find useful, but could use improvement or simplification:

https://github.com/GeriLife/wellbeing/blob/0d543bd0a5a1bc11e1fc15570649fa0edbb1badb/app/server/methods/charts/homeCharts.js#L9-L81

https://github.com/GeriLife/wellbeing/blob/0d543bd0a5a1bc11e1fc15570649fa0edbb1badb/app/server/methods/activities.js#L6-L39

**Comment by brylie** [comment]
Just the tab with the charts. In my previous branch, I had to refactor the trmplate code a bit, if I recall correctly.

**Comment by brylie** [comment]
I.e. the acitvit counts/minutes by type/facilitator should only be displayed on the first tab, so the templates need refactor. You can check out the branch where I have already done the refactor, to see the idea.

**Comment by brylie** [comment]
https://github.com/GeriLife/wellbeing/tree/home-profile-activities-charts-config-ui/app/client/views/home/activities

**Comment by brylie** [comment]
K, you don't have to use my commit, just take a look at the structure changes:
https://github.com/GeriLife/wellbeing/tree/home-profile-activities-charts-config-ui/app/client/views/home/activities

**Comment by marla-singer** [comment]
@brylie Another questions

What charts should be updated when a user change metrics counts/minutes? All of them or not all?

1. Activity summary by type
2. Activity counts by type
3. Activity counts by facilitator role

**Comment by brylie** [comment]
All of them should reflect the same metric and time-period.
