### ISSUE TITLE
Replace Homes resident activity levels charts with consolidated charts

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#323]
The Homes screen shows resident activity level percentages using horizontal bar charts. The charts are taking up unnecessary space with:
- separate bars for each activity level (poor, moderate, excellent)
- separate x-axis for each home

![current home activity levels](https://camo.githubusercontent.com/360f88af3495a0ab37a2eac4abf7e0c4ff981d88/68747470733a2f2f7261776769742e636f6d2f476572694c6966652f77656c6c6265696e672f646576656c6f702f646f63732f73637265656e73686f74732f486f6d65732d776974684d6f636b446174612d73696e676c6547726f75702e706e67)

## Task
Consolidate Homes resident activity level percentages chart, so that:
- activity level categories are stacked horizontally
- all homes within a group share a common x-axis

![screenshot from 2019-02-06 15-11-03](https://user-images.githubusercontent.com/17307/52343838-ebced980-2a21-11e9-9408-3e00c3d2d051.png)

Use Plotly.js to create the new chart component.

## Server-side data processing
To the extent possible, data processing should be done on the server. Create a method that builds on the existing server methods, but returns a single data response *similar to*:

- home 1
    - activity levels
        - low: 20
        - medium: 60
        - high: 20
- home 2
    - activity levels
        - low: 40
        - medium: 20
        - high: 40

Of course, take into account how the charting library will want the data to be shaped, so there as little client-side data parsing as possible.

**Comment by brylie** [comment]
Related to #242

**Comment by marla-singer** [comment]
@brylie If we replace the table to one chart then what to do with buttons are related to particular home? 
![image](https://user-images.githubusercontent.com/20643403/52841442-6e842280-310d-11e9-8d8b-47f9162ae39e.png)

**Comment by brylie** [comment]
@marla-singer good question. For now, lets just replace the individual home chart with a horizontal, stacked bar chart using Plotly.js.

**Comment by brylie** [comment]
That way, you won't need any backend code, and your PR will be similar to the other chart-replacement PRs.

**Comment by marla-singer** [comment]
Great
