### ISSUE TITLE
Test alternative UI for Add Activity form activityDate field

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#35]
The date field on the 'Add Activity' form currently uses Bootstrap date widget. Ideally, the date input will render in an accessible manner for mobile, tablet, and large screens, possibly using native date input UI. Try to get the activityDate field to render a native UI widget on most platforms (Android, iOS, Firefox, and Chrome), or consider using a library such as [pickadate.js](http://amsul.ca/pickadate.js/)

**Comment by brylie** [comment]
@ErikPel would you like to try improving the usability of the Add Activity form date field?

**Comment by brylie** [comment]
There is an [issue on the pickadate.js repository](https://github.com/amsul/pickadate.js/issues/837) regarding a previous usability bug.

**Comment by ErikPel** [comment]
Sure, I'll look into it today or tomorrow

**Comment by ErikPel** [comment]
I'm not sure if I understand the task.

Is the idea to not use the bootstrap date picker and instead show the native widgets for different platforms?

Could we use https://modernizr.com/ to check if the users platform can support input type="date" (which would show the native datepicker on iOS,android,Chrome and some others) and then if it's not supported by the users browser we give them something like https://jqueryui.com/datepicker/ or the bootstraps datepicker?

**Comment by brylie** [comment]
> Is the idea to not use the bootstrap date picker and instead show the native widgets for different platforms?

Yes, I think we should try using platform/browser native date pickers where possible, and show a user-friendly date picker where no default is available. 

Feel free to experiment with any date pickers. I just recommend pickadate.js, because it has a nice aesthetic and is easy to use on small screens.

**Comment by brylie** [comment]
[WebShims](https://afarkas.github.io/webshim/demos/) might also work for this feature.

Also, please let me know if working on this task does not seem like it will add significant benefit to the end-user. I.e. lets try to avoid wasting time on features that don't need attention (in the spirit of "don't fix it if it ain't broke", YAGNI, Lean development, etc.)

**Comment by ErikPel** [comment]
I was just thinking how this probably isn't worth the development time but then I found this

https://github.com/niftylettuce/bootstrap-datepicker-mobile
which pretty much does exactly the task we need (show native input if possible and then fallback to bootstrap datepicker)

It only supports  "MM/DD/YY" format currently but I doubt it would be difficult to fix.

Using that to save time makes the development time worth the result I think

**Comment by ErikPel** [comment]
With quick research I found that you can't change the format on native UI components so I'm not sure if we should just use MM/DD/YY or not do this at all.
 

What do you think @brylie ?

**Comment by brylie** [comment]
OK, good find. The date localization issue seems relatively important, but may be mitigated by the fact that the input is presented in a common, calendar widget.

One other thing to note, we want to [constrain the date selection to days within the previous week or less](https://github.com/GeriLife/wellbeing/pull/36/files). This helps encourage people to enter their activity records in a timely manner.
