### ISSUE TITLE
Ensure only admin users can access settings routes

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#350]
Reported by @shailee-m 

> In settings>users, if I am logged in as a non admin user should I be able to edit the groups I am assigned to? Currently it is allowed but I don't think it should be

**Comment by brylie** [comment]
We should ensure settings routes are only accessible by an admin.

**Comment by shailee-m** [comment]
@brylie  It is working as expected in `develop` branch

**Comment by brylie** [comment]
Does that mean that only admin users can access settings?
