### ISSUE TITLE
[Activity]: Number of rows per page is cropped

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#383]
Steps to Reproduce
1. Login to the application
2. Click on Activities
3. Enter 100 in "Show [ ] rows per page"
4. Notice, 100 is cropped . Thus, 3 digit numbers are cropped.

Screenshot : http://prntscr.com/njvcyw

**Comment by shailee-m** [comment]
@PayalChoksey17  this issue should be solved now, we now have dropdown for rows per page

**Comment by PayalChoksey17** [comment]
@shailee-m there is minor cropping visible. Please check the screenshot. 
<img width="938" alt="100" src="https://user-images.githubusercontent.com/41734649/61262234-33f8e180-a7a2-11e9-82ff-46f1aa0f7bf9.png">

**Comment by shailee-m** [comment]
@PayalChoksey17  still cannot reproduce
