### ISSUE TITLE
[Activity]: Adding activity from user level displays blank popup

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#385]
Steps to Reproduce
1. Login as User to the application
2. Click on Activities
3. Click on Add Activity
4. Notice, Activity popup screen is displayed blank without any functionality

Screenshot : http://prntscr.com/njvu1h

**Comment by shailee-m** [comment]
@brylie  @PayalChoksey17 Cannot reproduce this issue on the `develop` branch

**Comment by PayalChoksey17** [comment]
@shailee-m @brylie I am still able to reproduce this issue on develop branch. This issue is reproducible only at user level and not at admin level. Please check my video for more detailed steps. Let me know incase more details are required.

Video : https://www.loom.com/share/589a75c962d244e8b65fb2b128bfaa08

**Comment by shailee-m** [comment]
> It looks like the non-admin user may not be assigned to any groups. Can you verify? This bug, and others, might be expressed when assigning (or not assigning) non-admin users to groups, as the groups feature is rather new. Please prioritize the group-related test cases, as we want to be on good footing with group-based access control.

Yes precisely that is causing the issue here, the bug is there for a non-admin user. Will look into it.

**Comment by PayalChoksey17** [comment]
@shailee-m @brylie  Chrome Browser Version :  74.0.3729.131 (Official Build) (64-bit)

**Comment by PayalChoksey17** [comment]
This issue is verified and fixed.  Activity popup for user level is displayed correctly.

<img width="959" alt="User level" src="https://user-images.githubusercontent.com/41734649/57850658-0f14dc00-77fc-11e9-9a49-8ba059592f7d.png">
