### ISSUE TITLE
[Quick Add- Activity]: Unable to select previous month date/ Year

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#395]
Steps to Reproduce:
1. Login to application
2. Click on Activity in Quick Add
3. Click on Activity Date
4. Date picker is opened
5. Notice, user is not able to select previous month date. ( For example, April 28th )

Video : https://www.loom.com/share/504aae3aa6ff4a4f81d5bbb5a0c1242f

**Comment by shailee-m** [comment]
@PayalChoksey17 Activities are to be recorded for the past seven days from current date. Rest of all dates will be disabled.

**Comment by PayalChoksey17** [comment]
@shailee-m  Thanks for information on requirement. @brylie  Closing this ticket . Thanks
