### ISSUE TITLE
[Groups]: Adding long group name causes issue in UI on "Homes" page

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#400]
Steps to Reproduce:
1. Login to application 
2. Click on Homes
3. Click to Add Group
4. Enter Long name to Group and save it
5. Group name is added but "Add staff" and "Add Homes" are not aligned

Screenshot : http://prntscr.com/nmdqcf
Browser : Chrome
Version: 74.0.3729.131 (Official Build) (64-bit)

**Comment by brylie** [comment]
@PayalChoksey17, can you please upload the screenshot directly in the GitHub issues? GH allows images and animated GIFs to be embedded directly in the issue, so it is easier to see the image.

**Comment by PayalChoksey17** [comment]
Sure @brylie will be following it henceforth .

**Comment by brylie** [comment]
For this issue, we might consider adding a restriction to the Group Name length.

**Comment by shailee-m** [comment]
@brylie We can also restrict the display length here and display the full name in tooltip on hover
