### ISSUE TITLE
[Groups]: All groups are visible even when the user is added to only two groups

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#401]
Steps to Reproduce
1. Login to Admin A account
2. Go to Setting Page > Users
3. Click on groups to Edit the user group
4. Add two groups or more
5. Set the current user as admin ( Admin B)
6. Logout from Admin A
7. Login to Admin B
8. Click on Homes
9. Notice, all groups are added to Admin B

Note : Admin B should only view two group as set by Admin A

Video : https://www.loom.com/share/689b2d0c794a46fdb8edc518a518161b
Browser : Chrome | Version : 74

**Comment by brylie** [comment]
Admin users should see all groups, regardless of group assignment.

**Comment by PayalChoksey17** [comment]
Thank you for the clarification @brylie . Closing this ticket.
