### ISSUE TITLE
[Edit User Group]: Adding to many groups to a user hides "Save" and Cancel" button

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#402]
Steps to Reproduce:
1. Login as Admin 
2. Click on Settings
3. Click on Users
4. Click on Groups
5. Add 10 - 15 or more groups for the user
6. Notice, "Save" and Cancel" button are hidden

Screenshot : http://prntscr.com/nme0qy
Browser : Chrome | Version : 74.0.3729.131 (Official Build) (64-bit)

**Comment by brylie** [comment]
@all-contributors please add @PayalChoksey17 for bug

**Comment by PayalChoksey17** [comment]
This issue has been verified and fixed. 
<img width="960" alt="Scroll Bar" src="https://user-images.githubusercontent.com/41734649/57849903-336fb900-77fa-11e9-93de-7692ae5ccb78.png">
