### ISSUE TITLE
[Settings - Activity Types]: Adding a new activity type is not displayed in reports

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#414]
Steps
1. Login to the application
2. Click on Settings > Activity Types
3. Add a new activity type
4. Click on Reports
5. Notice, the new activity type is not displayed under report

Video : https://www.loom.com/share/6e12513c399d493c88a4dad19c34fd28

**Comment by shailee-m** [comment]
@PayalChoksey17 An activity type will show in the reports only after an activity of the given type is logged.

**Comment by PayalChoksey17** [comment]
@shailee-m Agree to this  :)

**Comment by PayalChoksey17** [comment]
@brylie  Closing this ticket.
