### ISSUE TITLE
[Edit User]: Duplicating the email address disables the save button

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#418]
Steps to Reproduce:
1. Login to the application
2. Click on Settings > USers
3. Click on Edit
4. Try to Duplicate the user with an existing user
5. Click on Save button
6. Notice, the Save button is disabled .

Note: If user enters another email address still save button is disabled
Screenshot :
<img width="943" alt="Edit User" src="https://user-images.githubusercontent.com/41734649/57774124-52594700-7737-11e9-884a-43dd861e6614.png">

**Comment by shailee-m** [comment]
Duplicating ideally should not be allowed, so by clicking on save, when the record is evaluated it fails, but error is not handled correctly.
