### ISSUE TITLE
Groups not sorting alphabetically on Homes page

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#419]
On the Homes page, groups should be sorted alphabetically. It was reported that this was not the case.

## Task
Ensure that Groups are sorted alphabetically on Homes page.

**Comment by PayalChoksey17** [comment]
@brylie  This issue is reproducible .
Ones the Group is added on Homes Page , group is created at the end of the list. Newest group is shown at the end of the list while the oldest is shown at the top.
Video :  https://www.loom.com/share/e5d41b901e434c33ae611c1a79693651
Repo Rate : 5/5

**Comment by brylie** [comment]
cc: @shailee-m

**Comment by shailee-m** [comment]
@brylie This issue should be resolved now. @PayalChoksey17 Can you please verify it again.

Attached video for reference: https://drive.google.com/file/d/1d8Tyb2Mgl2XGMgMJzJd74fWp5qzxv7JH/view

**Comment by brylie** [comment]
Please close this issue after verifying.

**Comment by PayalChoksey17** [comment]
@shailee-m @brylie  This issue is fixed. Groups are not sorted in alphabetical order on Homes Page. Closing this issue. 

Video: https://www.loom.com/share/7b02088708d145dba14419fb69d86956

**Comment by brylie** [comment]
@PayalChoksey17 and @shailee-m, do you remember who reported this issue?

**Comment by PayalChoksey17** [comment]
@brylie I suppose a customer reported this to you and you asked me to reproduce this issue.
