### ISSUE TITLE
[Language]: Drop list for language is cropped - UI Issue

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#423]
Steps to Reproduce :
1. Open the application
2. Click on Language drop list
3. Notice, the drop list is cropped - UI Issue

Screenshot : 
<img width="956" alt="Registration - UI Issue" src="https://user-images.githubusercontent.com/41734649/58171907-b4282c80-7cb4-11e9-8a26-d4fdeb064e93.png">

**Comment by shailee-m** [comment]
@PayalChoksey17 Not able to reproduce it

**Comment by PayalChoksey17** [comment]
@shailee-m closing this ticket as I am also not able to reproduce this issue at the moment. :)
