### ISSUE TITLE
[Assign a Manager]: Invalid error message is displayed all the time

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#436]
Steps to Reproduce:
1. Login to the application
2. Click on Homes
3. Click on assign Manager
4. Click on submit
5. Notice, error message is displayed
6. Close the Assign the manager popup
7. Open it again, still the error message is displayed 

Video : https://www.loom.com/share/4b21deaa18474b4ab633f51a4376f762
Screenshot  ( Clicking multiple times on submit) : 
![Screenshot_4](https://user-images.githubusercontent.com/41734649/59267536-24005600-8c68-11e9-8455-ae9dd9231050.png)

**Comment by shailee-m** [comment]
@PayalChoksey17 @brylie 
Yes this is because we do not autohide the messages anywhere.
We can do autohide and display this messages for 4-5 seconds. Although, if two actions are done within a span of those 4-5 seconds these messages will overlap. 

Also if we redirect to some other page with flashmessages enabled then it will show the message there. We need to write specific code for that.

**Comment by brylie** [comment]
I think the edge case of new page showing old flash messages isn't worth battling.

**Comment by brylie** [comment]
Auto-hide sounds like a good solution, and should already be supported by FlashMessages.

**Comment by PayalChoksey17** [comment]
@shailee-m  This issue is still reproducible if I click couple of time. Though it is intermittent issue 

Video : https://www.loom.com/share/9fbdbc85e1454eee963c9292dfc9b4ba

**Comment by shailee-m** [comment]
@payalChoksey17 yes like I said if remained untouched it disappears after 4 seconds.

It will also clear any old/seen messages but sometimes it takes a while for it to identify such messages. But the user is not going to click so many times on submit anyways so I guess it is not worth spending time on.

**Comment by PayalChoksey17** [comment]
@shailee-m  I agree with you. Lets not spend more time as  user won't click so many times at one time. Passing this issue. Thanks
