### ISSUE TITLE
[Assign a Manager]: Action column doesn't display anything

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#440]
Steps to Reproduce:
1. Login to application
2. Click on Homes
3. Click on Assign a Manager
4. Notice, under the action column no data is displayed. 

Screenshot : 
![Screenshot_7](https://user-images.githubusercontent.com/41734649/59270686-be17cc80-8c6f-11e9-990c-0ee90a73b2c2.png)

**Comment by shailee-m** [comment]
@PayalChoksey17  The action here is the remove button. The alignment was not proper. I have fixed it

**Comment by PayalChoksey17** [comment]
This issue is fixed .
Screenshot : <img width="498" alt="440" src="https://user-images.githubusercontent.com/41734649/59548489-b1e08780-8f6d-11e9-9b3d-566294184287.png">
