### ISSUE TITLE
[QA - Task]: Settings and Assign Manager Feature

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#443]
@brylie  Next features for Testing  

- Automation Testing is Settings feature. 
- Manual Testing : Testing the feature for Assign Manager

**Comment by PayalChoksey17** [comment]
Reported Assign Manager Issues 
1. #436 
2. #437 
3. #438 
4. #439 
5. #440 
6. #441 
7 #442

**Comment by brylie** [comment]
Thanks @PayalChoksey17. Now, make sure we test the deeper functionality, such that the Manager has the correct access permissions.

**Comment by shailee-m** [comment]
> Reported Assign Manager Issues
> 
> 1. #436
> 2. #437
> 3. #438
> 4. #439
> 5. #440
> 6. #441
>    7 #442

@PayalChoksey17 I have resolved issue 436, 437, 438, 439, 440, 441. You can verify them on the same branch i.e. 413-assign-manager-to-group.

Also please review my comment on 442

**Comment by PayalChoksey17** [comment]
@shailee-m Below issue are fixed and commented on the ticket
#437 
#438 
#439 
#440 
#441 

@shailee-m  for #436 Please check my comment on the ticket.  As per discussion passing this issue as well. Thanks

**Comment by PayalChoksey17** [comment]
Below scenario or permission are mentioned in #424 
Normal users can: add activity for residents in homes assigned to groups the user belongs to
Manager can: create and edit residencies in homes assigned to groups they manage
Admin has full privileges.

**Comment by PayalChoksey17** [comment]
@brylie : For automation I have completed Activity Types in Settings. Will push the entire code ones Setting feature is completed. Thanks

**Comment by PayalChoksey17** [comment]
@brylie  Manager permission has been tested and it works correctly. Commented on ticket #424 . Thanks

**Comment by brylie** [comment]
@shailee-m and @PayalChoksey17 great teamwork here!

@PayalChoksey17 can you add automation for these tests?

**Comment by PayalChoksey17** [comment]
@brylie Yes I will add to my list. Thanks

**Comment by PayalChoksey17** [comment]
@brylie closing this issue. As I have created separate task for automation scripts for settings. #447
