### ISSUE TITLE
Unable to logout from Resident page.

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#445]
Steps to Reproduce:
1. Login to the application as Admin or Non-admin Level
2. Click on Residents
3. Click to view resident
4. Logout from the page
5. Notice, the activities page is still displayed. 

Expected result : After clicking on logout from Activities page , login screen should be displayed
Actual result: Login screen is not displayed after user clicks on logout button 

Note : On Admin level, one can even click on Edit Resident.

Video : https://www.loom.com/share/3fe2d23f161243bdabddee29eb9a194f

**Comment by brylie** [comment]
What do you see in the browser console?

**Comment by PayalChoksey17** [comment]
@brylie This is what I see on browser console. 
<img width="960" alt="console" src="https://user-images.githubusercontent.com/41734649/59901443-e1cdd600-9418-11e9-9387-6b39df9faa33.png">

**Comment by shailee-m** [comment]
@brylie The comments in the routes/_config.js mentions that the `resident` route is allowed anonymus access, So even after logout the page displays information as it is an auth excluded route.

**Comment by brylie** [comment]
Ah that's right. Resident page should allow anonymous access.

@PayalChoksey17, please uodate the tests to allow for this case.
