### ISSUE TITLE
[Assign Manager]: Unable to delete/revoke the manager assigned 

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#455]
Steps to Reproduce
1. Open the application
2. Click on Homes
3. Click on Assign Manager for any Groups created on Homes Page
4. Add Manager
5.  Click "X" under actions to remove/revoke the assigned manager permissions
6. Notice, under Managers address the assigned manager is still displayed.

Note : If there are multiple managers assigned they will be removed, but the last Manager is not removed from the list.

Video : https://www.loom.com/share/64e5d9a788d1460c9fab0b981fdbc458

**Comment by brylie** [comment]
@shailee-m please confirm/fix this issue.

**Comment by brylie** [comment]
@PayalChoksey17 did you submit the form after clicking the X?

**Comment by PayalChoksey17** [comment]
@brylie after closing the form by clicking "X" on top right corner will close the form and when I open it again the Assigned manager is not displayed.

**Comment by brylie** [comment]
@PayalChoksey17 by closing the form without hitting "Save", you are cancelling the action. This gives users a chance to "bail out" without committing to accidental changes.

**Comment by PayalChoksey17** [comment]
@brylie but there is no " Save " button on it. Can you check below video with full action that I am performing. 
Video : https://www.loom.com/share/61989eda5bea43ae9184833024f5b2d7.

**Comment by brylie** [comment]
OK, thanks for the clarification. @shailee-m will you please review/fix?

**Comment by shailee-m** [comment]
Sure I will fix it.

**Comment by shailee-m** [comment]
@brylie Yes

**Comment by shailee-m** [comment]
> OK, thanks for the clarification. @shailee-m will you please review/fix?

@PayalChoksey17  I have fixed the bug in the branch the 413-assign-manager-to-group. Can you please verify it?

@brylie  Here is the commit: https://github.com/GeriLife/wellbeing/commit/6a4f1e659ee46ddab2238f8fd5f0198a26172e36

**Comment by PayalChoksey17** [comment]
@shailee-m  This issue is fixed correctly.  All assigned managers are deleted correctly. Thanks
@brylie  Closing this ticket as the issue is fixed.
Video : https://www.loom.com/share/52250f00fca94b87994234756d4880ff
