### ISSUE TITLE
[QA-Task]: Add Scripts for 'deactivate account on date' on Settings Page

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#459]
Create Automation scripts for Add 'deactivate account on date'

**Comment by PayalChoksey17** [comment]
Bugs Reported : 
#460

**Comment by shailee-m** [comment]
@brylie  @PayalChoksey17 Please refer to this branch `107-deactivate-user-on`.
#460: https://github.com/GeriLife/wellbeing/pull/466/commits/18cd6b885ec6ee69e141eaa6a02813ff79dcefab
#461: https://github.com/GeriLife/wellbeing/pull/466/commits/0d8c8b56d7ce13e4f3a50ceb0c64c868ae9d632c
#462: https://github.com/GeriLife/wellbeing/pull/466/commits/a45be8c83d1d18f1304a97202705216aa175c4a0
#464: https://github.com/GeriLife/wellbeing/pull/466/commits/1f0496908dade6c6d55c4152948f1788b561d366

**Comment by PayalChoksey17** [comment]
@shailee-m  Can you please check #468  seems there is some issue due to which I am not able to retest #460 #461 #462 #464 . Thanks.  Note, I pulled the code from this branch 107-deactivate-user-on.

**Comment by shailee-m** [comment]
> @shailee-m Can you please check #468 seems there is some issue due to which I am not able to retest #460 #461 #462 #464 . Thanks. Note, I pulled the code from this branch 107-deactivate-user-on.

@PayalChoksey17  Hi I am not able to reproduce this issue. Did you switch to 107-deactivate-user-on or pull the code from it into the older one?

**Comment by PayalChoksey17** [comment]
@shailee-m I did try again to pull the same branch 107-deactivate-user-on and now I am not able see the bug any more. Closing #468
