### ISSUE TITLE
[Deactivate User]: User is able to select invalid year.

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#461]
Steps to Reproduce

1. Open the application
2. Go to Settings > Users > Edit
3. Select 2019 as year
4. Select down arrow 
5. Notice, Invalid year is being displayed.

<img width="957" alt="Year" src="https://user-images.githubusercontent.com/41734649/60699126-32146000-9f10-11e9-9218-0e131ba43e53.png">

**Comment by shailee-m** [comment]
@PayalChoksey17  Here any number over 0 is considered valid, so I will set a maximum allowed date which is 1/1/2050. In the calendar dropdown all dates beyond that will be disabled but if the date is manually typed in the input box then it will validate only after submitting. So for manually typed dates it will allow to enter upto year 9999.
