### ISSUE TITLE
[Deactivate User]: Error message is hidden when invalid date is selected

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#463]
Steps to Reproduce

1. Open the application
2. Go to Settings > Users > Edit
3. Enter invalid date
4. Notice, error message is displayed behind the Edit User popup. Thus the message is hidden and not visible.

Screenshot : 
<img width="960" alt="validation 1" src="https://user-images.githubusercontent.com/41734649/60700027-ee235a00-9f13-11e9-83ba-c132dd2d2fa6.png">

**Comment by shailee-m** [comment]
@PayalChoksey17  I will resolve this with #430 and #431 as this issue is the same as #430
