### ISSUE TITLE
Filtering activities does not change the number of rows in table

### ISSUE THREAD

**Issue by shailee-m** [GeriLife/wellbeing#472]
Steps to reproduce:
https://drive.google.com/file/d/1YMx_UYq0fr4D57dCJr3q_4cNm7jvo4Dx/view

**Comment by PayalChoksey17** [comment]
@shailee-m  Also check this video. Seems to be similar. Let me know if you want me to create separate ticket for this. Thanks 
Video:  https://www.loom.com/share/f7083758ff664c0fb100763d2a7440fd

**Comment by shailee-m** [comment]
> @shailee-m Also check this video. Seems to be similar. Let me know if you want me to create separate ticket for this. Thanks
> Video: https://www.loom.com/share/f7083758ff664c0fb100763d2a7440fd

@PayalChoksey17  Yes it is the same. No need to create a separate card
