### ISSUE TITLE
[Activities]: Unable to delete an activities

### ISSUE THREAD

**Issue by PayalChoksey17** [GeriLife/wellbeing#475]
Steps to Reproduce
1. Login to the application
2. Click on Activities
3. Click  on Delete for any activity
4. Notice, the activity is not deleted.

Video : https://www.loom.com/share/879799eeee1a43dda09aa5fae1124fc2

**Comment by brylie** [comment]
Anything in the browser console?

**Comment by PayalChoksey17** [comment]
@brylie Added the video link for this issue with the browser console. 

https://www.loom.com/share/b3fa15cd59534c4aad40b3bc8482f8d5
