### ISSUE TITLE
"Deactivate on" field should be visible on Add User form

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#484]
Currently, the "Deactivate on" field is only visible when editing a user. It should also be visible when adding a user, so that managers can set the deactivation date at that point. If possible, both forms should share the same code.

**Comment by shailee-m** [comment]
> Currently, the "Deactivate on" field is only visible when editing a user. It should also be visible when adding a user, so that managers can set the deactivation date at that point. If possible, both forms should share the same code.


> Currently, the "Deactivate on" field is only visible when editing a user. It should also be visible when adding a user, so that managers can set the deactivation date at that point. If possible, both forms should share the same code.

@brylie  Add and edit modal do not share the same code as the logic for add and edit are a different, also the autoform schemas are slightly different

**Comment by brylie** [comment]
I believe these forms have significant overlap in form and function. See, for example, the Activity Form, to get an idea of how these forms might be combined:

https://github.com/GeriLife/wellbeing/tree/develop/app/client/views/activities/form

Is there a fundamental reason why these forms need to be defined distinctly?
