### ISSUE TITLE
Improve performance of All Homes Report chart(s)

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#501]
The All Homes Report currently aggregates a lot of data, particularly on GeriLife instances that have many residents and activities. This is a good candidate for initial performance improvements. Determine a way to pre-compute the daily activity values, so the chart can make a single, smaller query rather than relying on a large query (all activities) and time-consuming aggregation (group by activity type.

**Comment by shailee-m** [comment]
Is it okay to create another collection which calculates the activite count ,activity minutes by both month and week? It will have another column of the date on which it was last caclulated. There can be a cron that does this calculation at a given frequency like everyday or everyweek.

**Comment by brylie** [comment]
That sounds good.
