### ISSUE TITLE
Add "activity counts by facilitator role" to All Homes Report

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#502]
Service managers might like to see historic perspective of what role(s) have been coordinating their wellbeing activities. Design and develop one or more charts to convey a sense of the proportion of activities being coordinated by each role. This might take the form of a monthly aggregation, to match the other chart on the All Homes Report page.

**Comment by shailee-m** [comment]
@brylie Please approve the charts from the following list. Also let me know if there are any more aggregations that may be helpful according to you.

1. Graph showing total minutes of activity for each facilitator. (bar)
2. Average time spend by role on each activity (bar/pie)
3. Role by activity on which maximum time spend (table)
4. Count of activity types by facilitator role (bar)

**Comment by shailee-m** [comment]
Not sure how to calculate point number 2. But It can be a helpful statistic.

**Comment by brylie** [comment]
Let's start at the first level of aggregation, **activity counts** and **activity minutes** per **facilitator role**. Group the chart by month or day, similarly to how we have constructed the "activity counts and minutes by activity type" chart. 

![ActivityReport-MonthlyActivityCountStacked](https://user-images.githubusercontent.com/17307/71158553-d2570a80-224c-11ea-9f3e-d9f5b1147795.png)

The aggregation code for that chart can be reused or refactored, and a parameter added to group data by the facilitator role instead of activity type. Re-using the same method with an additional parameter will allow the chart components to fetch data asynchronously.

https://github.com/GeriLife/wellbeing/blob/05085a20cac754bb433d62cff5b486377d8ef0ce/app/client/views/report/report.js#L12-L31

https://github.com/GeriLife/wellbeing/blob/fc1df7af3502e9fc7a5f1e2f5887df320d72f345/app/server/methods/activities.js#L44-L57

Once we have refactored the aggregation code, let's discuss how to cache the data to speed up page requests.

**Comment by brylie** [comment]
Admittedly, this dashboard needs to be sketched, so we have a sense of what charts to show and how they communicate the story of the care community.
