### ISSUE TITLE
Update project dependencies to latest compatible versions

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#509]
There are several security updates available. Update the project dependencies to the latest compatible versions.

**Comment by shailee-m** [comment]
@brylie  After upgrading to meteor 1.9, the vue component throws a build error.
Here is the issue, https://github.com/meteor-vue/vue-meteor/issues/392 where I am expecting a resolution. 

For now, I can update the other packages without updating the meteor version or remove the vue component from front-page (if migrating to Vue is not a priority) and update meteor to version 1.9.

**Comment by brylie** [comment]
Migrating to Vue is not a priority at this time, so the 1.9 upgrade would be more important :-)

I suppose we can deprecate the Meteor Vue stuff if it is not too difficult. Thanks @shailee-m

**Comment by shailee-m** [comment]
I think we must hide all tests testing collection hooks untill this issue is resolved: https://github.com/hwillson/meteor-stub-collections/issues/35 . The collection hooks are not getting stubbed so tests related to it are failing.

**Comment by brylie** [comment]
OK, sounds good. How extensively do we use collection hooks? Might we just deprecate that package?

**Comment by shailee-m** [comment]
We mostly use allow-deny while adding/updating activities and residencies as in some client forms we are directly using the collection name to save the records.

**Comment by brylie** [comment]
OK, it looks like there will soon be a pull request to fix the regression. Let's keep things as-is. Disable the tests, if you feel it would be ok.
