### ISSUE TITLE
Maintenance tasks

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#525]
- [x] Adjust Code Climate to be more lenient
- [x] Fix some code to comply with Code Climate rules
- [x] Enable CI on the project repository (automatically run tests against pull requests)
- [x] Improve developer documentation
- [x] Get rid of collection hooks
- [x] Ensure all project dependencies are up to date (e.g. new Meteor release)
- [x] Separate frontend code from "backend" code
  - [x] E.g. forms that may be integrating directly with backend
- [x] Reduce charting library dependencies (e.g. deprecate NVD3 if it is still in use.)
- [x] PR template to add PR checks
- [x] Sorting in activities (Default by activityDate in descending order)
- [x] console error https://github.com/GeriLife/wellbeing/issues/537

**Comment by shailee-m** [comment]
@brylie  can you give me access to the project on code climate?

**Comment by brylie** [comment]
I couldn't see how to add you on Code climate. However, you can configure the settings via a .codeclimate file, if I recall correctly.

**Comment by shailee-m** [comment]
okay. it says I can add this repo only if I am listed as an owner on the organisation (https://github.com/orgs/GeriLife/people).

**Comment by brylie** [comment]
OK, for now just let me know which rules you would like adjusted and I'll make the changes.

**Comment by shailee-m** [comment]
> OK, for now just let me know which rules you would like adjusted and I'll make the changes.

For now, we can remove the constraint on the number of lines in a file and duplicate blocks across files. Also, the maximum number of lines in a single method must be increased.

**Comment by shailee-m** [comment]
For continuous integration as well, admin rights and access to the deployment server are required. I tried this on a local project. `Semaphore` is good for deployment (using meteor galaxy deployment server) 

https://medium.com/@sbr464/how-to-continuous-integration-for-meteor-galaxy-using-semaphore-ci-8bcd73b6bc9d

**Comment by brylie** [comment]
@shailee-m CodeClimate allows configuration to be specified via a config file:

https://docs.codeclimate.com/docs/advanced-configuration

Go ahead and open a pull request with the changes in a config.

**Comment by shailee-m** [comment]
I have a question about the row-wise subscriptions in the tables and Meteor account-related method calls on the client. Do we want to get rid of those too? may affect the performance.

**Comment by brylie** [comment]
Do the tables need to be reactive or would a row-wise method call suffice?

**Comment by shailee-m** [comment]
Yes reactivity in residents and activity tables is required if, what we need is that when the row is edited it must reflect in the table.  But I recall adding row-wise subscription in table for improving performance.

**Comment by brylie** [comment]
What about updating the row data in the form submit method/callback?

**Comment by shailee-m** [comment]
Yes that is what needs to be done, if we remove the subscription.

**Comment by brylie** [comment]
OK, let's take the callback approach. It's not as hipster, but takes us a step closer to being able to migrate to a different backend/frontend combo if needed.

**Comment by shailee-m** [comment]
I will be removing all direct db calls and subscriptions. Instead will use method call for crud and refresh on success.

When migrating the backedn to another backend system, we will have to implement custom login as the meteor users/accounts will not be useful. It can be done once the mysql tables are defined. So as on now I am leaving the roles check and login code as it is.

Also, for the forms there will be a dependency on the simpl-schema so there may be a few updates to  the collections schema once the new database is designed.

**Comment by shailee-m** [comment]
On the resident edit screen, the updates do not reflect automatically on the screen as the method.calls happen in individual component. We can add a refresh button which can be used by the user without reload.

**Comment by brylie** [comment]
Yes, or just refresh the page when the form submits? That is fairly standard.

**Comment by shailee-m** [comment]
> Yes, or just refresh the page when the form submits? That is fairly standard.

I realised that this issue is due to the data being fetched and passed to child template, whereas all updates are handled by child templates only. Now that subscription is not being used, we can do the get calls in the child template itself..

**Comment by shailee-m** [comment]
All CRUD has been moved to the backend. Some methods like userInfo and log-in/logout will have to be kept until we use the meteor user collections

**Comment by brylie** [comment]
@shailee-m please add the following issue as part of your work: https://github.com/GeriLife/wellbeing/issues/530

**Comment by shailee-m** [comment]
Adding tests in CI will not help as the testing libraries for meteor take more than one run to pass.

**Comment by shailee-m** [comment]
@brylie
Regarding the documentation task, I am adding some setup instructions in dev mode. With documentation, do we also want to add jsdocs for server methods?

**Comment by brylie** [comment]
@shailee-m could you please also investigate this issue? https://github.com/GeriLife/wellbeing/issues/537
