### ISSUE TITLE
Ensure all form submissions trigger page reload

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#530]
When submitting some forms, such as "Create New Group" or "Create New Home", the modal dialogue dismisses but the new group or home is not visible on the screen. The changes are, naturally, visible after the page reloads.

This is likely a result of us decoupling the frontend and backend code, and losing reactivity (which was planned).

## Task
- [ ] Ensure that a user sees the result of their action whenever submitting a form.
- [ ] Make sure modal forms trigger a page reload to render the inputted/updated data

**Comment by brylie** [comment]
@shailee-m I have added this task to the 1.1 milestone.

**Comment by shailee-m** [comment]
@brylie  yes on homes group I have noticed this. For the resident page, I have added a refresh button. For residency crud, activity and settings crud, I have already ensured reactivity.
