### ISSUE TITLE
All homes report chart not populating when upgrading existing deployment

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#532]
I upgraded an existing deployment to the latest (unreleased) version of GeriLife. The only noticeable bug is that the All Homes Report charts do not render:

![image](https://user-images.githubusercontent.com/17307/79946724-3434b480-8479-11ea-9ce0-26ef89497400.png)

## Task
- [x] Ensure All Homes Report chart data is available when upgrading existing projects
- [x] Generate data the first time the reports page is requested if it doesn't already exist

**Comment by brylie** [comment]
@shailee-m please see if you can diagnose/fix this bug prior to the 1.1 release :-)

**Comment by shailee-m** [comment]
If this is the first run, it will populate after the first cronjob is run which is set up to run at 12 am every day.
