### ISSUE TITLE
XLSX export for all activity and resident data

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#540]
Some potential and existing clients would like to work with GeriLife data in external tools. Excel is one of the primary tools available to many organizations, and XLSX format is widely supported among data processing tools/libraries.

## Task
- allow all resident and activity data to be exported from the administrative interface
  - Residents
  - Residencies
  - Activities
  - Homes
  - Groups

The data can be in separate sheets, if possible, or files.

**Comment by shailee-m** [comment]
@brylie I will add an option to export the file as xlsx. What is the preferred format, 1 xlsx file with multiple sheets or multiple xlsx files?
