### ISSUE TITLE
Release 1.1 bugs

### ISSUE THREAD

**Issue by shailee-m** [GeriLife/wellbeing#544]
- [x] Home Reports bug
- [x] Loading residents in home-edit page
- [x] Activity Add button should only be for Admin users
- [x] CSS fixes

**Comment by shailee-m** [comment]
@brylie The reports are now aggegated so there is no way to filter data according to the rights of the current user. Maybe we should aggregate data by each home. Let me know what you think of that. I think this is a crucial issue for the release.

**Comment by brylie** [comment]
Yes, let's aggregate data for each home separately and only send allowed data to the user.

**Comment by shailee-m** [comment]
> Yes, let's aggregate data for each home separately and only send allowed data to the user.

I have pushed these changes into the PR. It involves separating the rows by each home in a given activity. Can you validate the logic?

Also, I have done a round of QA on the App and all the issues I found I have fixed in the PR. let me know if you find anymore
